export const data = {
    "animaux": {
        "fr": [
            { "nom": "Tortue", "image": "tortue.jpg" },
            { "nom": "Chien", "image": "chien.jpg" },
            { "nom": "Coq", "image": "coq.jpg" },
            { "nom": "Pingouin", "image": "pingouin.jpg" },
            { "nom": "Chèvre", "image": "chevre.jpg" },
            { "nom": "Chat", "image": "chat.jpg" },
            { "nom": "Cheval", "image": "cheval.jpg" },
            { "nom": "Grenouille", "image": "grenouille.jpg" },
            { "nom": "Lion", "image": "lion.jpg" },
        ],
        "en": [
            { "nom": "Turtle", "image": "tortue.jpg" },
            { "nom": "Dog", "image": "chien.jpg" },
            { "nom": "Rooster", "image": "coq.jpg" },
            { "nom": "Penguin", "image": "pingouin.jpg" },
            { "nom": "Goat", "image": "chevre.jpg" },
            { "nom": "Cat", "image": "chat.jpg" },
            { "nom": "Horse", "image": "cheval.jpg" },
            { "nom": "Frog", "image": "grenouille.jpg" },
            { "nom": "Lion", "image": "lion.jpg" }
        ]
    },
    "pays":{
        "fr":[
            { "nom": "Afghanistan", "image": "drapeaux/Flag_of_the_Taliban.png" },
            { "nom": "Afrique du Sud", "image": "drapeaux/Flag_of_South_Africa.png" },
            { "nom": "Albanie", "image": "drapeaux/Flag_of_Albania.png" },
            { "nom": "Algérie", "image": "drapeaux/Flag_of_Algeria.png" },
            { "nom": "Allemagne", "image": "drapeaux/Flag_of_Germany.png" },
            { "nom": "Andore", "image": "drapeaux/Flag_of_Andorra.png" },
            { "nom": "Angola", "image": "drapeaux/Flag_of_Angola.png" },
            { "nom": "Antigua-et-Barbuda", "image": "drapeaux/Flag_of_Antigua_and_Barbuda.png" },
            { "nom": "Arabie saoudite", "image": "drapeaux/Flag_of_Saudi_Arabia.png" },
            { "nom": "Argentine", "image": "drapeaux/Flag_of_Argentina.svg" },
            { "nom": "Arménie", "image": "drapeaux/Flag_of_Armenia.png" },
            { "nom": "Australie", "image": "drapeaux/Flag_of_Australia.png" },
            { "nom": "Autriche", "image": "drapeaux/Flag_of_Austria.png" },
            { "nom": "Azerbaïdjan", "image": "drapeaux/Flag_of_Azerbaijan.png" },

            { "nom": "Bahamas", "image": "drapeaux/Flag_of_the_Bahamas.png" },
            { "nom": "Bahreïn", "image": "drapeaux/Flag_of_Bahrain.png" },
            { "nom": "Bangladesh", "image": "drapeaux/Flag_of_Bangladesh.svg" },
            { "nom": "Barbade", "image": "drapeaux/Flag_of_Barbados.svg" },
            { "nom": "Belgique", "image": "drapeaux/Flag_of_Belgium.svg" },
            { "nom": "Belize", "image": "drapeaux/Flag_of_Belize.svg" },
            { "nom": "Bénin", "image": "drapeaux/Flag_of_Benin.svg" },
            { "nom": "Bhoutan", "image": "drapeaux/Flag_of_Bhutan.svg" },
            { "nom": "Biélorussie", "image": "drapeaux/Flag_of_Belarus.svg" },
            { "nom": "Birmanie", "image": "drapeaux/Flag_of_Myanmar.svg" },
            { "nom": "Bolivie", "image": "drapeaux/Flag_of_Bolivia.svg" },
            { "nom": "Bosnie-Herzégovine", "image": "drapeaux/Flag_of_Bosnia_and_Herzegovina.svg" },
            { "nom": "Botswana", "image": "drapeaux/Flag_of_Botswana.svg" },
            { "nom": "Brésil", "image": "drapeaux/Flag_of_Brazil.svg" },
            { "nom": "Brunei", "image": "drapeaux/Flag_of_Brunei.svg" },
            { "nom": "Bulgarie", "image": "drapeaux/Flag_of_Bulgaria.svg" },
            { "nom": "Burkina Faso", "image": "drapeaux/Flag_of_Burkina_Faso.svg" },
            { "nom": "Burundi", "image": "drapeaux/Flag_of_Burundi.svg" },

            { "nom": "Cambodge", "image": "drapeaux/Flag_of_Cambodia.svg" },
            { "nom": "Cameroun", "image": "drapeaux/Flag_of_Cameroon.svg" },
            { "nom": "Canada", "image": "drapeaux/Flag_of_Canada.svg" },
            { "nom": "Cap-Vert", "image": "drapeaux/Flag_of_Cape_Verde.svg" },
            { "nom": "République centrafricaine", "image": "drapeaux/Flag_of_the_Central_African_Republic.svg" },
            { "nom": "Chili", "image": "drapeaux/Flag_of_Chile.svg" },
            { "nom": "Chine", "image": "drapeaux/Flag_of_the_People's_Republic_of_China.svg" },
            { "nom": "Chypre", "image": "drapeaux/Flag_of_Cyprus.svg" },
            { "nom": "Colombie", "image": "drapeaux/Flag_of_Colombia.svg" },
            { "nom": "Comores", "image": "drapeaux/Flag_of_the_Comoros.svg" },
            { "nom": "République démocratique du Congo", "image": "drapeaux/Flag_of_the_Democratic_Republic_of_the_Congo.svg" },
            { "nom": "République du Congo", "image": "drapeaux/Flag_of_the_Republic_of_the_Congo.svg" },
            { "nom": "Îles Cook", "image": "drapeaux/Flag_of_the_Cook Islands.svg" },
            { "nom": "Corée du Nord", "image": "drapeaux/Flag_of_North_Korea.svg" },
            { "nom": "Corée du Sud", "image": "drapeaux/Flag_of_South_Korea.svg" },
            { "nom": "Costa Rica", "image": "drapeaux/Flag_of_Costa_Rica.svg" },
            { "nom": "Côte d'Ivoire", "image": "drapeaux/Flag_of_Côte_d'Ivoire.svg" },
            { "nom": "Croatie", "image": "drapeaux/Flag_of_Croatia.svg" },
            { "nom": "Cuba", "image": "drapeaux/Flag_of_Cuba.svg" },

            { "nom": "Égypte", "image": "drapeaux/Flag_of_Egypt.svg" },
            { "nom": "Émirats arabes unis", "image": "drapeaux/Flag_of_the_United_Arab_Emirates.svg" },
            { "nom": "Équateur", "image": "drapeaux/Flag_of_Ecuador.svg" },
            { "nom": "Érythrée", "image": "drapeaux/Flag_of_Eritrea.svg" },
            { "nom": "Espagne", "image": "drapeaux/Flag_of_Spain.svg" },
            { "nom": "Estonie", "image": "drapeaux/Flag_of_Estonia.svg" },
            { "nom": "Eswatini", "image": "drapeaux/Flag_of_Eswatini.svg" },
            { "nom": "États-Unis", "image": "drapeaux/Flag_of_the_United_States.svg" },
            { "nom": "Éthiopie", "image": "drapeaux/Flag_of_Ethiopia.svg" },

            { "nom": "Fidji", "image": "drapeaux/Flag_of_Fiji.svg" },
            { "nom": "Finlande", "image": "drapeaux/Flag_of_Finland.svg" },
            { "nom": "France", "image": "drapeaux/Flag_of_France.svg" },

            { "nom": "Gabon", "image": "drapeaux/Flag_of_Gabon.svg" },
            { "nom": "Gambie", "image": "drapeaux/Flag_of_the_Gambia.svg" },
            { "nom": "Géorgie", "image": "drapeaux/Flag_of_Georgia.svg" },
            { "nom": "Ghana", "image": "drapeaux/Flag_of_Ghana.svg" },
            { "nom": "Grèce", "image": "drapeaux/Flag_of_Greece.svg" },
            { "nom": "Grenade", "image": "drapeaux/Flag_of_Grenada.svg" },
            { "nom": "Guatemala", "image": "drapeaux/Flag_of_Guatemala.svg" },
            { "nom": "Guinée", "image": "drapeaux/Flag_of_Guinea.svg" },
            { "nom": "Guinée-Bissau", "image": "drapeaux/Flag_of_Guinea-Bissau.svg" },
            { "nom": "Guinée équatoriale", "image": "drapeaux/Flag_of_Equatorial_Guinea.svg" },
            { "nom": "Guyana", "image": "drapeaux/Flag_of_Guyana.svg" },

            { "nom": "Haïti", "image": "drapeaux/Flag_of_Haiti.svg" },
            { "nom": "Honduras", "image": "drapeaux/Bandera_de_Honduras.svg" },
            { "nom": "Hongrie", "image": "drapeaux/Flag_of_Hungary.svg" },

            { "nom": "Inde", "image": "drapeaux/Flag_of_India.svg" },
            { "nom": "Indonésie", "image": "drapeaux/Flag_of_Indonesia.svg" },
            { "nom": "Irak", "image": "drapeaux/Flag_of_Iraq.svg" },
            { "nom": "Iran", "image": "drapeaux/Flag_of_Iran.svg" },
            { "nom": "Irlande", "image": "drapeaux/Flag_of_Ireland.svg" },
            { "nom": "Islande", "image": "drapeaux/Flag_of_Iceland.svg" },
            { "nom": "Israël", "image": "drapeaux/Flag_of_Israel.svg" },
            { "nom": "Italie", "image": "drapeaux/Flag_of_Italy.svg" },

            { "nom": "Jamaïque", "image": "drapeaux/Flag_of_Jamaica.svg" },
            { "nom": "Japon", "image": "drapeaux/Flag_of_Japan.svg" },
            { "nom": "Jordanie", "image": "drapeaux/Flag_of_Jordan.svg" },


            { "nom": "Kazakhstan", "image": "drapeaux/Flag_of_Kazakhstan.svg" },
            { "nom": "Kenya", "image": "drapeaux/Flag_of_Kenya.svg" },
            { "nom": "Kirghizistan", "image": "drapeaux/Flag_of_Kyrgyzstan.svg" },
            { "nom": "Kiribati", "image": "drapeaux/Flag_of_Kiribati.svg" },
            { "nom": "Koweït", "image": "drapeaux/Flag_of_Kuwait.svg" },

            { "nom": "Laos", "image": "drapeaux/Flag_of_Laos.svg" },
            { "nom": "Lesotho", "image": "drapeaux/Flag_of_Lesotho.svg" },
            { "nom": "Lettonie", "image": "drapeaux/Flag_of_Latvia.svg" },
            { "nom": "Liban", "image": "drapeaux/Flag_of_Lebanon.svg" },
            { "nom": "Liberia", "image": "drapeaux/Flag_of_Liberia.svg" },
            { "nom": "Libye", "image": "drapeaux/Flag_of_Libya.svg" },
            { "nom": "Liechtenstein", "image": "drapeaux/Flag_of_Liechtenstein.svg" },
            { "nom": "Lituanie", "image": "drapeaux/Flag_of_Lithuania.svg" },
            { "nom": "Luxembourg", "image": "drapeaux/Flag_of_Luxembourg.svg" },  

            { "nom": "Macédoine du Nord", "image": "drapeaux/Flag_of_North_Macedonia.svg" },
            { "nom": "Madagascar", "image": "drapeaux/Flag_of_Madagascar.svg" },
            { "nom": "Malaisie", "image": "drapeaux/Flag_of_Malaysia.svg" },
            { "nom": "Malawi", "image": "drapeaux/Flag_of_Malawi.svg" },
            { "nom": "Maldives", "image": "drapeaux/Flag_of_Maldives.svg" },
            { "nom": "Mali", "image": "drapeaux/Flag_of_Mali.svg" },
            { "nom": "Malte", "image": "drapeaux/Flag_of_Malta.svg" },
            { "nom": "Maroc", "image": "drapeaux/Flag_of_Morocco.svg" },
            { "nom": "Îles Marshall", "image": "drapeaux/Flag_of_the_Marshall_Islands.svg" },
            { "nom": "Maurice", "image": "drapeaux/Flag_of_Mauritius.svg" },
            { "nom": "Mauritanie", "image": "drapeaux/Flag_of_Mauritania.svg" },
            { "nom": "Mexique", "image": "drapeaux/Flag_of_Mexico.svg" },
            { "nom": "États fédérés de Micronésie", "image": "drapeaux/Flag_of_the_Federated_States_of_Micronesia.svg" },
            { "nom": "Moldavie", "image": "drapeaux/Flag_of_Moldova.svg" },
            { "nom": "Monaco", "image": "drapeaux/Flag_of_Monaco.svg" },
            { "nom": "Mongolie", "image": "drapeaux/Flag_of_Mongolia.svg" },
            { "nom": "Monténégro", "image": "drapeaux/Flag_of_Montenegro.svg" },
            { "nom": "Mozambique", "image": "drapeaux/Flag_of_Mozambique.svg" },

            { "nom": "Namibie", "image": "drapeaux/Namibia.svg" },
            { "nom": "Nauru", "image": "drapeaux/Flag_of_Nauru.svg" },
            { "nom": "Népal", "image": "drapeaux/Nepal.svg" },
            { "nom": "Nicaragua", "image": "drapeaux/Flag_of_Nicaragua.svg" },
            { "nom": "Niger", "image": "drapeaux/Flag_of_Niger.svg" },
            { "nom": "Nigeria", "image": "drapeaux/Nigeria.svg" },
            { "nom": "Niue", "image": "drapeaux/Niue.svg" },
            { "nom": "Norvège", "image": "drapeaux/Norway.svg" },
            { "nom": "Nouvelle-Zélande", "image": "drapeaux/Flag_of_New_Zealand.svg" },

            { "nom": "Oman", "image": "drapeaux/Flag_of_Oman.svg" },
            { "nom": "Ouganda", "image": "drapeaux/Flag_of_Uganda.svg" },
            { "nom": "Ouzbékistan", "image": "drapeaux/Flag_of_Uzbekistan.svg" },	  

            { "nom": "Pakistan", "image": "drapeaux/Pakistan.svg" },
            { "nom": "Palaos", "image": "drapeaux/Flag_of_Palau.svg" },
            { "nom": "Palestine", "image": "drapeaux/Flag_of_Palestine.svg" },
            { "nom": "Panama", "image": "drapeaux/Panama.svg" },
            { "nom": "Papouasie-Nouvelle-Guinée", "image": "drapeaux/Papua_New_Guinea.svg" },
            { "nom": "Paraguay", "image": "drapeaux/Flag_of_Paraguay.svg" },
            { "nom": "Pays-Bas", "image": "drapeaux/Flag_of_the_Netherlands.svg" },
            { "nom": "Pérou", "image": "drapeaux/Flag_of_Peru.svg" },
            { "nom": "Philippines", "image": "drapeaux/Philippines.svg" },
            { "nom": "Pologne", "image": "drapeaux/Flag_of_Poland.svg" },
            { "nom": "Portugal", "image": "drapeaux/Flag_of_Portugal.svg" },
            
            { "nom": "Qatar", "image": "drapeaux/Flag_of_Qatar.svg" },
            
            { "nom": "Roumanie", "image": "drapeaux/Flag_of_Romania.svg" },
            { "nom": "Royaume-Uni", "image": "drapeaux/Flag_of_the_United_Kingdom.svg" },
            { "nom": "Russie", "image": "drapeaux/Flag_of_Russia.svg" },
            { "nom": "Rwanda", "image": "drapeaux/Rwanda.svg" },

            { "nom": "Saint-Christophe-et-Niévès", "image": "drapeaux/Saint_Kitts_and_Nevis.svg" },
            { "nom": "Sainte-Lucie", "image": "drapeaux/Saint_Lucia.svg" },
            { "nom": "Saint-Marin", "image": "drapeaux/Flag_of_San_Marino.svg" },
            { "nom": "Saint-Vincent-et-les-Grenadines", "image": "drapeaux/Saint_Vincent_and_the_Grenadines.svg" },
            { "nom": "Salomon", "image": "drapeaux/Flag_of_the_Solomon_Islands.svg" },
            { "nom": "Salvador", "image": "drapeaux/Flag_of_El_Salvador.svg" },
            { "nom": "Samoa", "image": "drapeaux/Flag_of_Samoa.svg" },
            { "nom": "Sao Tomé-et-Principe", "image": "drapeaux/São_Tomé_and_Príncipe.svg" },
            { "nom": "Sénégal", "image": "drapeaux/Flag_of_Senegal.svg" },
            { "nom": "Serbie", "image": "drapeaux/Flag_of_Serbia.svg" },
            { "nom": "Seychelles", "image": "drapeaux/Seychelles.svg" },
            { "nom": "Sierra Leone", "image": "drapeaux/Flag_of_Sierra_Leone.svg" },
            { "nom": "Singapour", "image": "drapeaux/Flag_of_Singapore.svg" },
            { "nom": "Slovaquie", "image": "drapeaux/Slovakia.svg" },
            { "nom": "Slovénie", "image": "drapeaux/Flag_of_Slovenia.svg" },
            { "nom": "Somalie", "image": "drapeaux/Flag_of_Somalia.svg" },
            { "nom": "Soudan", "image": "drapeaux/Flag_of_Sudan.svg" },
            { "nom": "Soudan du Sud", "image": "drapeaux/Flag_of_South_Sudan.svg" },
            { "nom": "Sri Lanka", "image": "drapeaux/Flag_of_Sri_Lanka.svg" },
            { "nom": "Suède", "image": "drapeaux/Flag_of_Sweden.svg" },
            { "nom": "Suisse", "image": "drapeaux/Flag_of_Switzerland.svg" },
            { "nom": "Suriname", "image": "drapeaux/Flag_of_Suriname.svg" },
            { "nom": "Syrie", "image": "drapeaux/Flag_of_Syria.svg" },

            { "nom": "Tadjikistan", "image": "drapeaux/Flag_of_Tajikistan.svg" },
            { "nom": "Tanzanie", "image": "drapeaux/Tanzania.svg" },
            { "nom": "Tchad", "image": "drapeaux/Flag_of_Chad.svg" },
            { "nom": "Tchéquie", "image": "drapeaux/Flag_of_the_Czech_Republic.svg" },
            { "nom": "Thaïlande", "image": "drapeaux/Flag_of_Thailand.svg" },
            { "nom": "Timor oriental", "image": "drapeaux/Flag_of_Timor-Leste.svg" },
            { "nom": "Togo", "image": "drapeaux/Flag_of_Togo.svg" },
            { "nom": "Tonga", "image": "drapeaux/Flag_of_Tonga.svg" },
            { "nom": "Trinité-et-Tobago", "image": "drapeaux/Flag_of_Trinidad_and_Tobago.svg" },
            { "nom": "Tunisie", "image": "drapeaux/Flag_of_Tunisia.svg" },
            { "nom": "Turkménistan", "image": "drapeaux/Flag_of_Turkmenistan.svg" },
            { "nom": "Turquie", "image": "drapeaux/Turkey.svg" },
            { "nom": "Tuvalu", "image": "drapeaux/Tuvalu.svg" },

            { "nom": "Ukraine", "image": "drapeaux/Flag_of_Ukraine.svg" },
            { "nom": "Uruguay", "image": "drapeaux/Flag_of_Uruguay.svg" },

            { "nom": "Vanuatu", "image": "drapeaux/Flag_of_Vanuatu.svg" },
            { "nom": "Vatican", "image": "drapeaux/Vatican.svg" },
            { "nom": "Venezuela", "image": "drapeaux/Flag_of_Venezuela.svg" },
            { "nom": "Viêt Nam", "image": "drapeaux/Flag_of_Vietnam.svg" },

            { "nom": "Yémen", "image": "drapeaux/Flag_of_Yemen.svg" },

            { "nom": "Zambie", "image": "drapeaux/Zambia.svg" },
            { "nom": "Zimbabwe", "image": "drapeaux/Zimbabwe.svg" },
           


        ],
        "en": [
            { "name": "Afghanistan", "image": "drapeaux/Flag_of_the_Taliban.png" },
            { "name": "South Africa", "image": "drapeaux/Flag_of_South_Africa.png" },
            { "name": "Albania", "image": "drapeaux/Flag_of_Albania.png" },
            { "name": "Algeria", "image": "drapeaux/Flag_of_Algeria.png" },
            { "name": "Germany", "image": "drapeaux/Flag_of_Germany.png" },
            { "name": "Andorra", "image": "drapeaux/Flag_of_Andorra.png" },
            { "name": "Angola", "image": "drapeaux/Flag_of_Angola.png" },
            { "name": "Antigua and Barbuda", "image": "drapeaux/Flag_of_Antigua_and_Barbuda.png" },
            { "name": "Saudi Arabia", "image": "drapeaux/Flag_of_Saudi_Arabia.png" },
            { "name": "Argentina", "image": "drapeaux/Flag_of_Argentina.svg" },
            { "name": "Armenia", "image": "drapeaux/Flag_of_Armenia.png" },
            { "name": "Australia", "image": "drapeaux/Flag_of_Australia.png" },
            { "name": "Austria", "image": "drapeaux/Flag_of_Austria.png" },
            { "name": "Azerbaijan", "image": "drapeaux/Flag_of_Azerbaijan.png" },
            
            { "name": "Bahamas", "image": "drapeaux/Flag_of_the_Bahamas.png" },
            { "name": "Bahrain", "image": "drapeaux/Flag_of_Bahrain.png" },
            { "name": "Bangladesh", "image": "drapeaux/Flag_of_Bangladesh.svg" },
            { "name": "Barbados", "image": "drapeaux/Flag_of_Barbados.svg" },
            { "name": "Belgium", "image": "drapeaux/Flag_of_Belgium.svg" },
            { "name": "Belize", "image": "drapeaux/Flag_of_Belize.svg" },
            { "name": "Benin", "image": "drapeaux/Flag_of_Benin.svg" },
            { "name": "Bhutan", "image": "drapeaux/Flag_of_Bhutan.svg" },
            { "name": "Belarus", "image": "drapeaux/Flag_of_Belarus.svg" },
            { "name": "Myanmar", "image": "drapeaux/Flag_of_Myanmar.svg" },
            { "name": "Bolivia", "image": "drapeaux/Flag_of_Bolivia.svg" },
            { "name": "Bosnia and Herzegovina", "image": "drapeaux/Flag_of_Bosnia_and_Herzegovina.svg" },
            { "name": "Botswana", "image": "drapeaux/Flag_of_Botswana.svg" },
            { "name": "Brazil", "image": "drapeaux/Flag_of_Brazil.svg" },
            { "name": "Brunei", "image": "drapeaux/Flag_of_Brunei.svg" },
            { "name": "Bulgaria", "image": "drapeaux/Flag_of_Bulgaria.svg" },
            { "name": "Burkina Faso", "image": "drapeaux/Flag_of_Burkina_Faso.svg" },
            { "name": "Burundi", "image": "drapeaux/Flag_of_Burundi.svg" },
    
            { "name": "Cambodia", "image": "drapeaux/Flag_of_Cambodia.svg" },
            { "name": "Cameroon", "image": "drapeaux/Flag_of_Cameroon.svg" },
            { "name": "Canada", "image": "drapeaux/Flag_of_Canada.svg" },
            { "name": "Cape Verde", "image": "drapeaux/Flag_of_Cape_Verde.svg" },
            { "name": "Central African Republic", "image": "drapeaux/Flag_of_the_Central_African_Republic.svg" },
            { "name": "Chile", "image": "drapeaux/Flag_of_Chile.svg" },
            { "name": "China", "image": "drapeaux/Flag_of_the_People's_Republic_of_China.svg" },
            { "name": "Cyprus", "image": "drapeaux/Flag_of_Cyprus.svg" },
            { "name": "Colombia", "image": "drapeaux/Flag_of_Colombia.svg" },
            { "name": "Comoros", "image": "drapeaux/Flag_of_the_Comoros.svg" },
            { "name": "Democratic Republic of the Congo", "image": "drapeaux/Flag_of_the_Democratic_Republic_of_the_Congo.svg" },
            { "name": "Republic of the Congo", "image": "drapeaux/Flag_of_the_Republic_of_the_Congo.svg" },
            { "name": "Cook Islands", "image": "drapeaux/Flag_of_the_Cook Islands.svg" },
            { "name": "North Korea", "image": "drapeaux/Flag_of_North_Korea.svg" },
            { "name": "South Korea", "image": "drapeaux/Flag_of_South_Korea.svg" },
            { "name": "Costa Rica", "image": "drapeaux/Flag_of_Costa_Rica.svg" },
            { "name": "Ivory Coast", "image": "drapeaux/Flag_of_Côte_d'Ivoire.svg" },
            { "name": "Croatia", "image": "drapeaux/Flag_of_Croatia.svg" },
            { "name": "Cuba", "image": "drapeaux/Flag_of_Cuba.svg" },
    
            { "name": "Egypt", "image": "drapeaux/Flag_of_Egypt.svg" },
            { "name": "United Arab Emirates", "image": "drapeaux/Flag_of_the_United_Arab_Emirates.svg" },
            { "name": "Ecuador", "image": "drapeaux/Flag_of_Ecuador.svg" },
            { "name": "Eritrea", "image": "drapeaux/Flag_of_Eritrea.svg" },
            { "name": "Spain", "image": "drapeaux/Flag_of_Spain.svg" },
            { "name": "Estonia", "image": "drapeaux/Flag_of_Estonia.svg" },
            { "name": "Eswatini", "image": "drapeaux/Flag_of_Eswatini.svg" },
            { "name": "United States", "image": "drapeaux/Flag_of_the_United_States.svg" },
            { "name": "Ethiopia", "image": "drapeaux/Flag_of_Ethiopia.svg" },
    
            { "name": "Fiji", "image": "drapeaux/Flag_of_Fiji.svg" },
            { "name": "Finland", "image": "drapeaux/Flag_of_Finland.svg" },
            { "name": "France", "image": "drapeaux/Flag_of_France.svg" },
    
            { "name": "Gabon", "image": "drapeaux/Flag_of_Gabon.svg" },
            { "name": "Gambia", "image": "drapeaux/Flag_of_the_Gambia.svg" },
            { "name": "Georgia", "image": "drapeaux/Flag_of_Georgia.svg" },
            { "name": "Ghana", "image": "drapeaux/Flag_of_Ghana.svg" },
            { "name": "Greece", "image": "drapeaux/Flag_of_Greece.svg" },
            { "name": "Grenada", "image": "drapeaux/Flag_of_Grenada.svg" },
            { "name": "Guatemala", "image": "drapeaux/Flag_of_Guatemala.svg" },
            { "name": "Guinea", "image": "drapeaux/Flag_of_Guinea.svg" },
            { "name": "Guinea-Bissau", "image": "drapeaux/Flag_of_Guinea-Bissau.svg" },
            { "name": "Equatorial Guinea", "image": "drapeaux/Flag_of_Equatorial_Guinea.svg" },
            { "name": "Guyana", "image": "drapeaux/Flag_of_Guyana.svg" },
            { "name": "Haiti", "image": "drapeaux/Flag_of_Haiti.svg" },
            { "name": "Honduras", "image": "drapeaux/Bandera_de_Honduras.svg" },
            { "name": "Hungary", "image": "drapeaux/Flag_of_Hungary.svg" },

            { "name": "India", "image": "drapeaux/Flag_of_India.svg" },
            { "name": "Indonesia", "image": "drapeaux/Flag_of_Indonesia.svg" },
            { "name": "Iraq", "image": "drapeaux/Flag_of_Iraq.svg" },
            { "name": "Iran", "image": "drapeaux/Flag_of_Iran.svg" },
            { "name": "Ireland", "image": "drapeaux/Flag_of_Ireland.svg" },
            { "name": "Iceland", "image": "drapeaux/Flag_of_Iceland.svg" },
            { "name": "Israel", "image": "drapeaux/Flag_of_Israel.svg" },
            { "name": "Italy", "image": "drapeaux/Flag_of_Italy.svg" },

            { "name": "Jamaica", "image": "drapeaux/Flag_of_Jamaica.svg" },
            { "name": "Japan", "image": "drapeaux/Flag_of_Japan.svg" },
            { "name": "Jordan", "image": "drapeaux/Flag_of_Jordan.svg" },

            { "name": "Kazakhstan", "image": "drapeaux/Flag_of_Kazakhstan.svg" },
            { "name": "Kenya", "image": "drapeaux/Flag_of_Kenya.svg" },
            { "name": "Kyrgyzstan", "image": "drapeaux/Flag_of_Kyrgyzstan.svg" },
            { "name": "Kiribati", "image": "drapeaux/Flag_of_Kiribati.svg" },
            { "name": "Kuwait", "image": "drapeaux/Flag_of_Kuwait.svg" },

            { "name": "Laos", "image": "drapeaux/Flag_of_Laos.svg" },
            { "name": "Lesotho", "image": "drapeaux/Flag_of_Lesotho.svg" },
            { "name": "Latvia", "image": "drapeaux/Flag_of_Latvia.svg" },
            { "name": "Lebanon", "image": "drapeaux/Flag_of_Lebanon.svg" },
            { "name": "Liberia", "image": "drapeaux/Flag_of_Liberia.svg" },
            { "name": "Libya", "image": "drapeaux/Flag_of_Libya.svg" },
            { "name": "Liechtenstein", "image": "drapeaux/Flag_of_Liechtenstein.svg" },
            { "name": "Lithuania", "image": "drapeaux/Flag_of_Lithuania.svg" },
            { "name": "Luxembourg", "image": "drapeaux/Flag_of_Luxembourg.svg" },

            { "nom": "North Macedonia", "image": "drapeaux/Flag_of_North_Macedonia.svg" },
            { "nom": "Madagascar", "image": "drapeaux/Flag_of_Madagascar.svg" },
            { "nom": "Malaysia", "image": "drapeaux/Flag_of_Malaysia.svg" },
            { "nom": "Malawi", "image": "drapeaux/Flag_of_Malawi.svg" },
            { "nom": "Maldives", "image": "drapeaux/Flag_of_Maldives.svg" },
            { "nom": "Mali", "image": "drapeaux/Flag_of_Mali.svg" },
            { "nom": "Malta", "image": "drapeaux/Flag_of_Malta.svg" },
            { "nom": "Morocco", "image": "drapeaux/Flag_of_Morocco.svg" },
            { "nom": "Marshall Islands", "image": "drapeaux/Flag_of_the_Marshall_Islands.svg" },
            { "nom": "Mauritius", "image": "drapeaux/Flag_of_Mauritius.svg" },
            { "nom": "Mauritania", "image": "drapeaux/Flag_of_Mauritania.svg" },
            { "nom": "Mexico", "image": "drapeaux/Flag_of_Mexico.svg" },
            { "nom": "Federated States of Micronesia", "image": "drapeaux/Flag_of_the_Federated_States_of_Micronesia.svg" },
            { "nom": "Moldova", "image": "drapeaux/Flag_of_Moldova.svg" },
            { "nom": "Monaco", "image": "drapeaux/Flag_of_Monaco.svg" },
            { "nom": "Mongolia", "image": "drapeaux/Flag_of_Mongolia.svg" },
            { "nom": "Montenegro", "image": "drapeaux/Flag_of_Montenegro.svg" },
            { "nom": "Mozambique", "image": "drapeaux/Flag_of_Mozambique.svg" },

            { "nom": "Namibia", "image": "drapeaux/Namibia.svg" },
            { "nom": "Nauru", "image": "drapeaux/Flag_of_Nauru.svg" },
            { "nom": "Nepal", "image": "drapeaux/Nepal.svg" },
            { "nom": "Nicaragua", "image": "drapeaux/Flag_of_Nicaragua.svg" },
            { "nom": "Niger", "image": "drapeaux/Flag_of_Niger.svg" },
            { "nom": "Nigeria", "image": "drapeaux/Nigeria.svg" },
            { "nom": "Niue", "image": "drapeaux/Niue.svg" },
            { "nom": "Norway", "image": "drapeaux/Norway.svg" },
            { "nom": "New Zealand", "image": "drapeaux/Flag_of_New_Zealand.svg" },

            { "nom": "Oman", "image": "drapeaux/Flag_of_Oman.svg" },
            { "nom": "Uganda", "image": "drapeaux/Flag_of_Uganda.svg" },
            { "nom": "Uzbekistan", "image": "drapeaux/Flag_of_Uzbekistan.svg" },

            { "nom": "Pakistan", "image": "drapeaux/Pakistan.svg" },
            { "nom": "Palau", "image": "drapeaux/Flag_of_Palau.svg" },
            { "nom": "Palestine", "image": "drapeaux/Flag_of_Palestine.svg" },
            { "nom": "Panama", "image": "drapeaux/Panama.svg" },
            { "nom": "Papua New Guinea", "image": "drapeaux/Papua_New_Guinea.svg" },
            { "nom": "Paraguay", "image": "drapeaux/Flag_of_Paraguay.svg" },
            { "nom": "Netherlands", "image": "drapeaux/Flag_of_the_Netherlands.svg" },
            { "nom": "Peru", "image": "drapeaux/Flag_of_Peru.svg" },
            { "nom": "Philippines", "image": "drapeaux/Philippines.svg" },
            { "nom": "Poland", "image": "drapeaux/Flag_of_Poland.svg" },
            { "nom": "Portugal", "image": "drapeaux/Flag_of_Portugal.svg" },

            { "nom": "Qatar", "image": "drapeaux/Flag_of_Qatar.svg" },

            { "nom": "Romania", "image": "drapeaux/Flag_of_Romania.svg" },
            { "nom": "United Kingdom", "image": "drapeaux/Flag_of_the_United_Kingdom.svg" },
            { "nom": "Russia", "image": "drapeaux/Flag_of_Russia.svg" },
            { "nom": "Rwanda", "image": "drapeaux/Flag_of_Rwanda.svg" },
    
            { "nom": "Saint Kitts and Nevis", "image": "drapeaux/Flag_of_Saint_Kitts_and_Nevis.svg" },
            { "nom": "Saint Vincent and the Grenadines", "image": "drapeaux/Flag_of_Saint_Vincent_and_the_Grenadines.svg" },
            { "nom": "Saint Lucia", "image": "drapeaux/Flag_of_Saint_Lucia.svg" },
            { "nom": "Solomon Islands", "image": "drapeaux/Flag_of_the_Solomon_Islands.svg" },
            { "nom": "El Salvador", "image": "drapeaux/Flag_of_El_Salvador.svg" },
            { "nom": "Samoa", "image": "drapeaux/Flag_of_Samoa.svg" },
            { "nom": "San Marino", "image": "drapeaux/Flag_of_San_Marino.svg" },
            { "nom": "Sao Tome and Principe", "image": "drapeaux/Flag_of_Sao_Tome_and_Principe.svg" },
            { "nom": "Saudi Arabia", "image": "drapeaux/Flag_of_Saudi_Arabia.svg" },
            { "nom": "Senegal", "image": "drapeaux/Flag_of_Senegal.svg" },
            { "nom": "Serbia", "image": "drapeaux/Flag_of_Serbia.svg" },
            { "nom": "Seychelles", "image": "drapeaux/Flag_of_Seychelles.svg" },
            { "nom": "Sierra Leone", "image": "drapeaux/Flag_of_Sierra_Leone.svg" },
            { "nom": "Singapore", "image": "drapeaux/Flag_of_Singapore.svg" },
            { "nom": "Slovakia", "image": "drapeaux/Flag_of_Slovakia.svg" },
            { "nom": "Slovenia", "image": "drapeaux/Flag_of_Slovenia.svg" },
            { "nom": "Somalia", "image": "drapeaux/Flag_of_Somalia.svg" },
            { "nom": "Sudan", "image": "drapeaux/Flag_of_Sudan.svg" },
            { "nom": "South Sudan", "image": "drapeaux/Flag_of_South_Sudan.svg" },
            { "nom": "Sri Lanka", "image": "drapeaux/Flag_of_Sri_Lanka.svg" },
            { "nom": "Sweden", "image": "drapeaux/Flag_of_Sweden.svg" },
            { "nom": "Switzerland", "image": "drapeaux/Flag_of_Switzerland.svg" },
            { "nom": "Suriname", "image": "drapeaux/Flag_of_Suriname.svg" },
            { "nom": "Syria", "image": "drapeaux/Flag_of_Syria.svg" },
    
            { "nom": "Tajikistan", "image": "drapeaux/Flag_of_Tajikistan.svg" },
            { "nom": "Tanzania", "image": "drapeaux/Flag_of_Tanzania.svg" },
            { "nom": "Chad", "image": "drapeaux/Flag_of_Chad.svg" },
            { "nom": "Thailand", "image": "drapeaux/Flag_of_Thailand.svg" },
            { "nom": "East Timor", "image": "drapeaux/Flag_of_East_Timor.svg" },
            { "nom": "Togo", "image": "drapeaux/Flag_of_Togo.svg" },
            { "nom": "Tonga", "image": "drapeaux/Flag_of_Tonga.svg" },
            { "nom": "Trinidad and Tobago", "image": "drapeaux/Flag_of_Trinidad_and_Tobago.svg" },
            { "nom": "Tunisia", "image": "drapeaux/Flag_of_Tunisia.svg" },
            { "nom": "Turkmenistan", "image": "drapeaux/Flag_of_Turkmenistan.svg" },
            { "nom": "Turkey", "image": "drapeaux/Flag_of_Turkey.svg" },
            { "nom": "Tuvalu", "image": "drapeaux/Flag_of_Tuvalu.svg" },
            { "nom": "Uganda", "image": "drapeaux/Flag_of_Uganda.svg" },
            
            { "nom": "Ukraine", "image": "drapeaux/Flag_of_Ukraine.svg" },
            { "nom": "Uruguay", "image": "drapeaux/Flag_of_Uruguay.svg" },
            { "nom": "Uzbekistan", "image": "drapeaux/Flag_of_Uzbekistan.svg" },

            { "nom": "Vanuatu", "image": "drapeaux/Flag_of_Vanuatu.svg" },
            { "nom": "Vatican City", "image": "drapeaux/Flag_of_the_Vatican_City.svg" },
            { "nom": "Venezuela", "image": "drapeaux/Flag_of_Venezuela.svg" },
            { "nom": "Vietnam", "image": "drapeaux/Flag_of_Vietnam.svg" },

            { "nom": "Yemen", "image": "drapeaux/Flag_of_Yemen.svg" },

            { "nom": "Zambia", "image": "drapeaux/Flag_of_Zambia.svg" },
            { "nom": "Zimbabwe", "image": "drapeaux/Flag_of_Zimbabwe.svg" }
        ]
    }
};
