export const data = {
    "animaux": {
        "fr": [
            { "nom": "Tortue", "image": "tortue.jpg" },
            { "nom": "Chien", "image": "chien.jpg" },
            { "nom": "Coq", "image": "coq.jpg" },
            { "nom": "Pingouin", "image": "pingouin.jpg" },
            { "nom": "Chèvre", "image": "chevre.jpg" },
            { "nom": "Chat", "image": "chat.jpg" },
            { "nom": "Cheval", "image": "cheval.jpg" },
            { "nom": "Grenouille", "image": "grenouille.jpg" },
            { "nom": "Lion", "image": "lion.jpg" },
        ],
        "en": [
            { "nom": "Turtle", "image": "tortue.jpg" },
            { "nom": "Dog", "image": "chien.jpg" },
            { "nom": "Rooster", "image": "coq.jpg" },
            { "nom": "Penguin", "image": "pingouin.jpg" },
            { "nom": "Goat", "image": "chevre.jpg" },
            { "nom": "Cat", "image": "chat.jpg" },
            { "nom": "Horse", "image": "cheval.jpg" },
            { "nom": "Frog", "image": "grenouille.jpg" },
            { "nom": "Lion", "image": "lion.jpg" }
        ]
    },
    "pays":{
        "fr":[
            { "nom": "Afghanistan", "image": "drapeaux/Flag_of_the_Taliban.png" },
            { "nom": "Afrique du Sud", "image": "drapeaux/Flag_of_South_Africa.png" },
            { "nom": "Albanie", "image": "drapeaux/Flag_of_Albania.png" },
            { "nom": "Algérie", "image": "drapeaux/Flag_of_Algeria.png" },
            { "nom": "Allemagne", "image": "drapeaux/Flag_of_Germany.png" },
            { "nom": "Andore", "image": "drapeaux/Flag_of_Andorra.png" },
            { "nom": "Angola", "image": "drapeaux/Flag_of_Angola.png" },
            { "nom": "Antigua-et-Barbuda", "image": "drapeaux/Flag_of_Antigua_and_Barbuda.png" },
            { "nom": "Arabie saoudite", "image": "drapeaux/Flag_of_Saudi_Arabia.png" },
            { "nom": "Argentine", "image": "drapeaux/Flag_of_Argentina.svg" },
            { "nom": "Arménie", "image": "drapeaux/Flag_of_Armenia.png" },
            { "nom": "Australie", "image": "drapeaux/Flag_of_Australia.png" },
            { "nom": "Autriche", "image": "drapeaux/Flag_of_Austria.png" },
            { "nom": "Azerbaïdjan", "image": "drapeaux/Flag_of_Azerbaijan.png" },

            { "nom": "Bahamas", "image": "drapeaux/Flag_of_the_Bahamas.png" },
            { "nom": "Bahreïn", "image": "drapeaux/Flag_of_Bahrain.png" },
            { "nom": "Bangladesh", "image": "drapeaux/Flag_of_Bangladesh.svg" },
            { "nom": "Barbade", "image": "drapeaux/Flag_of_Barbados.svg" },
            { "nom": "Belgique", "image": "drapeaux/Flag_of_Belgium.svg" },
            { "nom": "Belize", "image": "drapeaux/Flag_of_Belize.svg" },
            { "nom": "Bénin", "image": "drapeaux/Flag_of_Benin.svg" },
            { "nom": "Bhoutan", "image": "drapeaux/Flag_of_Bhutan.svg" },
            { "nom": "Biélorussie", "image": "drapeaux/Flag_of_Belarus.svg" },
            { "nom": "Birmanie", "image": "drapeaux/Flag_of_Myanmar.svg" },
            { "nom": "Bolivie", "image": "drapeaux/Flag_of_Bolivia.svg" },
            { "nom": "Bosnie-Herzégovine", "image": "drapeaux/Flag_of_Bosnia_and_Herzegovina.svg" },
            { "nom": "Botswana", "image": "drapeaux/Flag_of_Botswana.svg" },
            { "nom": "Brésil", "image": "drapeaux/Flag_of_Brazil.svg" },
            { "nom": "Brunei", "image": "drapeaux/Flag_of_Brunei.svg" },
            { "nom": "Bulgarie", "image": "drapeaux/Flag_of_Bulgaria.svg" },
            { "nom": "Burkina Faso", "image": "drapeaux/Flag_of_Burkina_Faso.svg" },
            { "nom": "Burundi", "image": "drapeaux/Flag_of_Burundi.svg" },

            { "nom": "Cambodge", "image": "drapeaux/Flag_of_Cambodia.svg" },
            { "nom": "Cameroun", "image": "drapeaux/Flag_of_Cameroon.svg" },
            { "nom": "Canada", "image": "drapeaux/Flag_of_Canada.svg" },
            { "nom": "Cap-Vert", "image": "drapeaux/Flag_of_Cape_Verde.svg" },
            { "nom": "République centrafricaine", "image": "drapeaux/Flag_of_the_Central_African_Republic.svg" },
            { "nom": "Chili", "image": "drapeaux/Flag_of_Chile.svg" },
            { "nom": "Chine", "image": "drapeaux/Flag_of_the_People's_Republic_of_China.svg" },
            { "nom": "Chypre", "image": "drapeaux/Flag_of_Cyprus.svg" },
            { "nom": "Colombie", "image": "drapeaux/Flag_of_Colombia.svg" },
            { "nom": "Comores", "image": "drapeaux/Flag_of_the_Comoros.svg" },
            { "nom": "République démocratique du Congo", "image": "drapeaux/Flag_of_the_Democratic_Republic_of_the_Congo.svg" },
            { "nom": "République du Congo", "image": "drapeaux/Flag_of_the_Republic_of_the_Congo.svg" },
            { "nom": "Îles Cook", "image": "drapeaux/Flag_of_the_Cook Islands.svg" },
            { "nom": "Corée du Nord", "image": "drapeaux/Flag_of_North_Korea.svg" },
            { "nom": "Corée du Sud", "image": "drapeaux/Flag_of_South_Korea.svg" },
            { "nom": "Costa Rica", "image": "drapeaux/Flag_of_Costa_Rica.svg" },
            { "nom": "Côte d'Ivoire", "image": "drapeaux/Flag_of_Côte_d'Ivoire.svg" },
            { "nom": "Croatie", "image": "drapeaux/Flag_of_Croatia.svg" },
            { "nom": "Cuba", "image": "drapeaux/Flag_of_Cuba.svg" },

            { "nom": "Égypte", "image": "drapeaux/Flag_of_Egypt.svg" },
            { "nom": "Émirats arabes unis", "image": "drapeaux/Flag_of_the_United_Arab_Emirates.svg" },
            { "nom": "Équateur", "image": "drapeaux/Flag_of_Ecuador.svg" },
            { "nom": "Érythrée", "image": "drapeaux/Flag_of_Eritrea.svg" },
            { "nom": "Espagne", "image": "drapeaux/Flag_of_Spain.svg" },
            { "nom": "Estonie", "image": "drapeaux/Flag_of_Estonia.svg" },
            { "nom": "Eswatini", "image": "drapeaux/Flag_of_Eswatini.svg" },
            { "nom": "États-Unis", "image": "drapeaux/Flag_of_the_United_States.svg" },
            { "nom": "Éthiopie", "image": "drapeaux/Flag_of_Ethiopia.svg" },

            { "nom": "Fidji", "image": "drapeaux/Flag_of_Fiji.svg" },
            { "nom": "Finlande", "image": "drapeaux/Flag_of_Finland.svg" },
            { "nom": "France", "image": "drapeaux/Flag_of_France.svg" },

            { "nom": "Gabon", "image": "drapeaux/Flag_of_Gabon.svg" },
            { "nom": "Gambie", "image": "drapeaux/Flag_of_the_Gambia.svg" },
            { "nom": "Géorgie", "image": "drapeaux/Flag_of_Georgia.svg" },
            { "nom": "Ghana", "image": "drapeaux/Flag_of_Ghana.svg" },
            { "nom": "Grèce", "image": "drapeaux/Flag_of_Greece.svg" },
            { "nom": "Grenade", "image": "drapeaux/Flag_of_Grenada.svg" },
            { "nom": "Guatemala", "image": "drapeaux/Flag_of_Guatemala.svg" },
            { "nom": "Guinée", "image": "drapeaux/Flag_of_Guinea.svg" },
            { "nom": "Guinée-Bissau", "image": "drapeaux/Flag_of_Guinea-Bissau.svg" },
            { "nom": "Guinée équatoriale", "image": "drapeaux/Flag_of_Equatorial_Guinea.svg" },
            { "nom": "Guyana", "image": "drapeaux/Flag_of_Guyana.svg" },

            { "nom": "Haïti", "image": "drapeaux/Flag_of_Haiti.svg" },
            { "nom": "Honduras", "image": "drapeaux/Bandera_de_Honduras.svg" },
            { "nom": "Hongrie", "image": "drapeaux/Flag_of_Hungary.svg" },

            { "nom": "Inde", "image": "drapeaux/Flag_of_India.svg" },
            { "nom": "Indonésie", "image": "drapeaux/Flag_of_Indonesia.svg" },
            { "nom": "Irak", "image": "drapeaux/Flag_of_Iraq.svg" },
            { "nom": "Iran", "image": "drapeaux/Flag_of_Iran.svg" },
            { "nom": "Irlande", "image": "drapeaux/Flag_of_Ireland.svg" },
            { "nom": "Islande", "image": "drapeaux/Flag_of_Iceland.svg" },
            { "nom": "Israël", "image": "drapeaux/Flag_of_Israel.svg" },
            { "nom": "Italie", "image": "drapeaux/Flag_of_Italy.svg" },

            { "nom": "Jamaïque", "image": "drapeaux/Flag_of_Jamaica.svg" },
            { "nom": "Japon", "image": "drapeaux/Flag_of_Japan.svg" },
            { "nom": "Jordanie", "image": "drapeaux/Flag_of_Jordan.svg" },


            { "nom": "Kazakhstan", "image": "drapeaux/Flag_of_Kazakhstan.svg" },
            { "nom": "Kenya", "image": "drapeaux/Flag_of_Kenya.svg" },
            { "nom": "Kirghizistan", "image": "drapeaux/Flag_of_Kyrgyzstan.svg" },
            { "nom": "Kiribati", "image": "drapeaux/Flag_of_Kiribati.svg" },
            { "nom": "Koweït", "image": "drapeaux/Flag_of_Kuwait.svg" },

            { "nom": "Laos", "image": "drapeaux/Flag_of_Laos.svg" },
            { "nom": "Lesotho", "image": "drapeaux/Flag_of_Lesotho.svg" },
            { "nom": "Lettonie", "image": "drapeaux/Flag_of_Latvia.svg" },
            { "nom": "Liban", "image": "drapeaux/Flag_of_Lebanon.svg" },
            { "nom": "Liberia", "image": "drapeaux/Flag_of_Liberia.svg" },
            { "nom": "Libye", "image": "drapeaux/Flag_of_Libya.svg" },
            { "nom": "Liechtenstein", "image": "drapeaux/Flag_of_Liechtenstein.svg" },
            { "nom": "Lituanie", "image": "drapeaux/Flag_of_Lithuania.svg" },
            { "nom": "Luxembourg", "image": "drapeaux/Flag_of_Luxembourg.svg" },  

            { "nom": "Macédoine du Nord", "image": "drapeaux/Flag_of_North_Macedonia.svg" },
            { "nom": "Madagascar", "image": "drapeaux/Flag_of_Madagascar.svg" },
            { "nom": "Malaisie", "image": "drapeaux/Flag_of_Malaysia.svg" },
            { "nom": "Malawi", "image": "drapeaux/Flag_of_Malawi.svg" },
            { "nom": "Maldives", "image": "drapeaux/Flag_of_Maldives.svg" },
            { "nom": "Mali", "image": "drapeaux/Flag_of_Mali.svg" },
            { "nom": "Malte", "image": "drapeaux/Flag_of_Malta.svg" },
            { "nom": "Maroc", "image": "drapeaux/Flag_of_Morocco.svg" },
            { "nom": "Îles Marshall", "image": "drapeaux/Flag_of_the_Marshall_Islands.svg" },
            { "nom": "Maurice", "image": "drapeaux/Flag_of_Mauritius.svg" },
            { "nom": "Mauritanie", "image": "drapeaux/Flag_of_Mauritania.svg" },
            { "nom": "Mexique", "image": "drapeaux/Flag_of_Mexico.svg" },
            { "nom": "États fédérés de Micronésie", "image": "drapeaux/Flag_of_the_Federated_States_of_Micronesia.svg" },
            { "nom": "Moldavie", "image": "drapeaux/Flag_of_Moldova.svg" },
            { "nom": "Monaco", "image": "drapeaux/Flag_of_Monaco.svg" },
            { "nom": "Mongolie", "image": "drapeaux/Flag_of_Mongolia.svg" },
            { "nom": "Monténégro", "image": "drapeaux/Flag_of_Montenegro.svg" },
            { "nom": "Mozambique", "image": "drapeaux/Flag_of_Mozambique.svg" },

            { "nom": "Namibie", "image": "drapeaux/Namibia.svg" },
            { "nom": "Nauru", "image": "drapeaux/Flag_of_Nauru.svg" },
            { "nom": "Népal", "image": "drapeaux/Nepal.svg" },
            { "nom": "Nicaragua", "image": "drapeaux/Flag_of_Nicaragua.svg" },
            { "nom": "Niger", "image": "drapeaux/Flag_of_Niger.svg" },
            { "nom": "Nigeria", "image": "drapeaux/Nigeria.svg" },
            { "nom": "Niue", "image": "drapeaux/Niue.svg" },
            { "nom": "Norvège", "image": "drapeaux/Norway.svg" },
            { "nom": "Nouvelle-Zélande", "image": "drapeaux/Flag_of_New_Zealand.svg" },



            { "nom": "", "image": "drapeaux/" },
            { "nom": "", "image": "drapeaux/" },
            { "nom": "", "image": "drapeaux/" },







        ]
    }
};
